# Generated by Django 4.1.3 on 2024-11-05 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing_app', '0002_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='testing',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='testing_app.company'),
        ),
    ]
